file_format: "1"
id: ergotravel
name: Ergotravel
type: shield
url: https://github.com/jpconstantineau/ErgoTravel
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - ergotravel_left
  - ergotravel_right
out:
  - usb
  - ble